### ISSUE TITLE
How to submit?

### ISSUE THREAD

**Issue by hoangvu12** [reacttips-dev/codebases#17]
I tried clone this repo to submit a codebase, but I can't.

![image](https://user-images.githubusercontent.com/68330291/135388662-fb5f124f-3b33-4efc-9fbc-0092a6ea5421.png)

What should I do?

**Comment by ladifire** [comment]
@hoangvu12 
I guess you see this error in window. So try following guide may be help:
[https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows](https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows)
Or this is quick reference from above link:
> You can circumvent this by using another Git client on Windows or set core.longpaths to true as explained in other answers.
> ```git config --system core.longpaths true```
