### ISSUE TITLE
What method do you use to get the source codes?

### ISSUE THREAD

**Issue by jhonnyalphas** [reacttips-dev/codebases#8]

**Comment by bboy114crew** [comment]
If the web app enables source-map in production you can inspect and get it :D In some cases, you can't view actual code in source-map even it enables.

**Comment by jhonnyalphas** [comment]
that is not illegal?. maybe soon they will take down the repository by dmca.

**Comment by bboy114crew** [comment]
@jhonnyalphas  I don't think so. Because if those companies enable source-map it's mean they intend to share it (I guess). As you can see we mention in the readme it good for reading and studying, but not recommended for using in product.
